[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$IGGGHjxB$ULmC5/i67P6FZ5magkYm71"
  ]

[http.routers.api]
  rule = "Host(`monitor.bmis.asset-boxx.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"